### ISSUE TITLE
Error while using encodie_images.py file when trying to run it in colab

### ISSUE THREAD

**Issue by KShivendu** [Puzer/stylegan#29]
`Traceback (most recent call last):
  File "encode_images.py", line 80, in <module>
    main()
  File "encode_images.py", line 51, in main
    generator_network, discriminator_network, Gs_network = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.`

I have duplicated pickle file in my Google drive as the quota was exceeding. But, now I am getting this error. Is is because of copying or something else ? 

According to [this Stackoverlow post](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key) ,  maybe the file itself has been corrupted. If it's the case , Is there any mirror link for the same file which can be used safely ?

**Comment by ApurvaDani** [comment]
Facing a similar error.
Did you find a solution for this?

**Comment by KShivendu** [comment]
Nope.

**Comment by JohnParkerLee** [comment]
Trying to set 'get links' settings to 'Anyone with the link'
![image](https://user-images.githubusercontent.com/39893619/95652901-ff9bde80-0b26-11eb-8dc2-adf78736a3b3.png)
